# Modified version of the deb-to-ipa workflow. 
# Do note that this can only inject one tweak at a time.
# Feel free to make a PR to add support for multiple tweaks if you'd like!!
name: The Tweak Injection... thing... tool?

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to tweak"
        required: true
      ipa:
        description: "Direct URL to IPA"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies and download the specified files
        run: |
          sudo apt install libplist-utils xmlstarlet libxml2-utils -y
          curl -L -o $PWD/tweak.dylib "${{ github.event.inputs.deb }}"
          curl -L -o $PWD/app.ipa "${{ github.event.inputs.ipa }}"
          
      - name: Install Azule and inject the tweak into the IPA
        run: |
          git clone https://github.com/Al4ise/Azule ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule
          azule -i $PWD/app.ipa -f $PWD/tweak.dylib -o /tmp/tweaked.ipa

      - name: Upload tweaked IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Tweaked App
          path: /tmp/tweaked.ipa
