name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to tweak"
        required: true
      ipa:
        description: "Direct URL to IPA"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          curl -L -o ${{ github.workspace }}/tweak.dylib "${{ github.event.inputs.deb }}"
          curl -L -o ${{ github.workspace }}/app.ipa "${{ github.event.inputs.ipa }}"
          git clone https://github.com/Al4ise/Azule Azule
          mv app.ipa Azule
          mv tweak.dylib Azule
          cd Azule
          chmod +x azule
          ./azule

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: App
          path: ${{ github.workspace }}/App.ipa
